"""create admin demo project

Revision ID: 5742191f06e5
Revises:
Create Date: 2026-08-09 23:47:49.989642

Review upgrade() and downgrade() before applying this migration.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5742191f06e5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("demo",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_demo_project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        info={"oldman_app_label": "demo", "oldman_managed": True},
    )
    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('admin_demo_project', 'demo', TRUE, '5742191f06e5')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'admin_demo_project' AND app_label = 'demo'")
    op.drop_table("admin_demo_project")
    # ### end Alembic commands ###
